model: FOSSIL

embedding_size: 64

order_len: 1
alpha: 0.2

loss_type: 'CE'
learning_rate: 0.01
reg_weights: [0.001, 0.001]

train_neg_sample_args: ~

clip_grad_norm:
  max_norm: 5.0

enable_amp: false
enable_scaler: false
