experiments:
- id: 03-04/BERT4Rec-Feb-07-2026_23-27-19
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/BERT4Rec-Feb-07-2026_23-27-19.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: BERT4Rec
  dataset_save_path: /home/hygo2025/Documents/experimentos/mg/03-04/realestate-SequentialDataset.pth
  wandb_config: wandb:p1msj5qq
- id: 03-04/BPR-Feb-07-2026_10-40-54
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/BPR-Feb-07-2026_10-40-54.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: BPR
  wandb_config: wandb:5su1k068
- id: 03-04/Caser-Feb-07-2026_23-45-43
  enabled: true
  eval_batch_size: 64
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/Caser-Feb-07-2026_23-45-43.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: Caser
  wandb_config: wandb:0gm17auy
- id: 03-04/FOSSIL-Feb-07-2026_11-03-33
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/FOSSIL-Feb-07-2026_11-03-33.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: FOSSIL
  wandb_config: wandb:p9jt2o1y
- id: 03-04/FPMC-Feb-07-2026_13-10-45
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/FPMC-Feb-07-2026_13-10-45.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: FPMC
  wandb_config: wandb:4riv0zwi
- id: 03-04/GRU4Rec-Feb-07-2026_16-33-25
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/GRU4Rec-Feb-07-2026_16-33-25.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: GRU4Rec
  wandb_config: wandb:ibtnfh8t
- id: 03-04/ItemKNN-Feb-07-2026_09-43-30
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/ItemKNN-Feb-07-2026_09-43-30.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: ItemKNN
  wandb_config: wandb:wu4f8qu4
- id: 03-04/LightGCN-Feb-07-2026_19-34-40
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/LightGCN-Feb-07-2026_19-34-40.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: LightGCN
  wandb_config: wandb:dy34n34i
- id: 03-04/NARM-Feb-07-2026_10-50-12
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/NARM-Feb-07-2026_10-50-12.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: NARM
  wandb_config: wandb:jd1aqxem
- id: 03-04/NextItNet-Feb-07-2026_15-25-16
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/NextItNet-Feb-07-2026_15-25-16.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: NextItNet
  wandb_config: wandb:lbm9xjem
- id: 03-04/Pop-Feb-07-2026_09-27-18
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/Pop-Feb-07-2026_09-27-18.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: Pop
  wandb_config: wandb:8xr5iy0c
- id: 03-04/Random-Feb-07-2026_09-24-08
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/Random-Feb-07-2026_09-24-08.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: Random
  wandb_config: wandb:87btvdcd
- id: 03-04/SASRec-Feb-07-2026_09-24-52
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/SASRec-Feb-07-2026_09-24-52.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: SASRec
  eval_batch_size: 2048
  wandb_config: wandb:sxsuul9p
- id: 03-04/TransRec-Feb-07-2026_09-03-59
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/03-04/TransRec-Feb-07-2026_09-03-59.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/03-04
  dataset: realestate
  model: TransRec
  wandb_config: wandb:sssdscwr
  eval_batch_size: 64
- id: 04-05/BERT4Rec-Feb-09-2026_00-35-08
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/BERT4Rec-Feb-09-2026_00-35-08.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: BERT4Rec
  wandb_config: wandb:boz7stwc
- id: 04-05/BPR-Feb-08-2026_10-01-46
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/BPR-Feb-08-2026_10-01-46.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: BPR
  wandb_config: wandb:hgj3kgxb
- id: 04-05/Caser-Feb-09-2026_00-32-58
  enabled: true
  eval_batch_size: 64
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/Caser-Feb-09-2026_00-32-58.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: Caser
  wandb_config: wandb:7gsaxvo9
- id: 04-05/FOSSIL-Feb-08-2026_10-07-11
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/FOSSIL-Feb-08-2026_10-07-11.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: FOSSIL
  wandb_config: wandb:m42kj1ex
- id: 04-05/FPMC-Feb-08-2026_18-36-12
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/FPMC-Feb-08-2026_18-36-12.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: FPMC
  wandb_config: wandb:rfjg9muv
- id: 04-05/GRU4Rec-Feb-08-2026_18-42-37
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/GRU4Rec-Feb-08-2026_18-42-37.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: GRU4Rec
  wandb_config: wandb:xttw1489
- id: 04-05/ItemKNN-Feb-08-2026_10-11-31
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/ItemKNN-Feb-08-2026_10-11-31.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: ItemKNN
  wandb_config: wandb:x72kn4ly
- id: 04-05/LightGCN-Feb-08-2026_18-38-18
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/LightGCN-Feb-08-2026_18-38-18.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: LightGCN
  wandb_config: wandb:mlnbtni9
- id: 04-05/NARM-Feb-08-2026_18-42-33
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/NARM-Feb-08-2026_18-42-33.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: NARM
  wandb_config: wandb:x5g29buh
- id: 04-05/NextItNet-Feb-08-2026_23-27-54
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/NextItNet-Feb-08-2026_23-27-54.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: NextItNet
  wandb_config: wandb:7pemihl3
- id: 04-05/Pop-Feb-08-2026_10-08-01
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/Pop-Feb-08-2026_10-08-01.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: Pop
  wandb_config: wandb:wkobtadl
- id: 04-05/Random-Feb-08-2026_10-02-13
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/Random-Feb-08-2026_10-02-13.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: Random
  wandb_config: wandb:gvjvzahf
- id: 04-05/SASRec-Feb-08-2026_23-29-49
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/SASRec-Feb-08-2026_23-29-49.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: SASRec
  eval_batch_size: 2048
  wandb_config: wandb:9icgvtee
- id: 04-05/TransRec-Feb-08-2026_23-30-02
  enabled: true
  checkpoint: /home/hygo2025/Documents/experimentos/mg/04-05/TransRec-Feb-08-2026_23-30-02.pth
  data_path: /home/hygo2025/Documents/experimentos/mg/04-05
  dataset: realestate
  model: TransRec
  wandb_config: wandb:6bkukfep
  eval_batch_size: 64
