dataset: realestate
data_path: /full_path_project_folder/outputs/data/recbole

raw_data:
  listings_raw_path: /data_path/data/listings
  events_raw_path: /data_path/data/events

  events_processed_path: /data_path/data/processed_data/events
  listings_processed_path: /data_path/data/processed_data/listings
  sessions_path: /full_path_project_folder/outputs/data/recbole/sessions_for_api.parquet

  listing_id_mapping_path: /data_path/data/processed_mapping/listing_id_mapping
  user_id_mapping_path: /data_path/data/processed_mapping/user_id_mapping
  session_id_mapping_path: /data_path/data/processed_mapping/session_id_mapping
  user_sessions_path: /data_path/data/processed_mapping/user_sessions

  events_path: /data_path/data/processed_data/events
  listings_path: /data_path/data/processed_data/listings

  output_path: /full_path_project_folder/outputs/data/recbole
  base_path: /data_path/data

data_preparation:
  start_date: "2024-06-01"
  end_date: "2024-07-01"
  min_session_length: 2
  max_session_length: 50
  min_item_freq: 5

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
SESSION_ID_FIELD: user_id

load_col:
  inter: [user_id, item_id, timestamp]

eval_args:
  split:
    LS: valid_and_test
  order: TO
  group_by: user
  mode:
    valid: uni100
    test: full
eval_neg_sample_args:
  distribution: uniform
  sample_num: 100


eval_step: 2
metrics: [Recall, MRR, NDCG, Hit]
topk: [5, 10, 20]
valid_metric: MRR@10

MAX_ITEM_LIST_LENGTH: 50

epochs: 80
embedding_size: 64
train_batch_size: 2048
eval_batch_size: 2048
learning_rate: 0.001
train_neg_sample_args: ~

stopping_step: 3
valid_metric_bigger: true

device: cuda
gpu_id: 0
worker: 12
seed: 42
state: DEBUG

reproducibility: true

enable_amp: true
enable_scaler: true

checkpoint_dir: outputs/saved
save_dataset: true
save_dataloaders: false
show_progress: true

log_wandb: true
wandb_project: "wandb_project"
wandb_group: ""
tensorboard: false

canonical_id:
  geohash_precision: 7

output:
  results_dir: outputs/results
  model_export_dir: outputs/models
  logs_dir: outputs/logs
  tensorboard_dir: log_tensorboard
