dataset: realestate
data_path: /home/hygo2025/Development/projects/fermi/outputs/data/recbole

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
SESSION_ID_FIELD: user_id

load_col:
  inter: [user_id, item_id, timestamp]

eval_args:
  split:
    LS: valid_and_test
  order: TO
  group_by: user
  mode:
    valid: uni100
    test: uni100

eval_neg_sample_args:
  distribution: uniform
  sample_num: 99

metrics: [Recall, MRR, NDCG, Hit]
topk: [5, 10, 20]
valid_metric: MRR@10

MAX_ITEM_LIST_LENGTH: 50

epochs: 30
train_batch_size: 4096
eval_batch_size: 4096
learning_rate: 0.001
train_neg_sample_args: ~

stopping_step: 5
valid_metric_bigger: true

gpu_id: 0
use_gpu: true
seed: 42
reproducibility: true

log_wandb: false
show_progress: false
